/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.oscarmaestre.jminilogo;

/**
 *
 * @author usuario
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBarBarraMenus = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuGuardarComo = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuCortar = new javax.swing.JMenuItem();
        menuCopiar = new javax.swing.JMenuItem();
        menuCambiarFuente = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuMostrarAyuda = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBarBarraMenus.setName("barraMenus"); // NOI18N

        menuArchivo.setText("Archivo");

        menuNuevo.setText("Nuevo");
        menuArchivo.add(menuNuevo);

        menuAbrir.setText("Abrir");
        menuAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAbrirMouseClicked(evt);
            }
        });
        menuArchivo.add(menuAbrir);

        menuGuardar.setText("Guardar");
        menuArchivo.add(menuGuardar);

        menuGuardarComo.setText("Guardar como...");
        menuArchivo.add(menuGuardarComo);

        menuSalir.setText("Salir");
        menuArchivo.add(menuSalir);

        menuBarBarraMenus.add(menuArchivo);

        menuEdicion.setText("Edicion");

        menuCortar.setText("Cortar");
        menuEdicion.add(menuCortar);

        menuCopiar.setText("Copiar");
        menuEdicion.add(menuCopiar);

        menuCambiarFuente.setText("Pegar");
        menuEdicion.add(menuCambiarFuente);

        jMenuItem4.setText("Cambiar fuente");
        menuEdicion.add(jMenuItem4);

        menuBarBarraMenus.add(menuEdicion);

        menuAyuda.setText("Ayuda");

        menuMostrarAyuda.setText("Mostrar ayuda");
        menuAyuda.add(menuMostrarAyuda);

        menuAcercaDe.setText("Acerca de");
        menuAyuda.add(menuAcercaDe);

        menuBarBarraMenus.add(menuAyuda);

        setJMenuBar(menuBarBarraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAbrirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAbrirMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    protected javax.swing.JMenuItem jMenuItem4;
    protected javax.swing.JMenuItem menuAbrir;
    protected javax.swing.JMenuItem menuAcercaDe;
    protected javax.swing.JMenu menuArchivo;
    protected javax.swing.JMenu menuAyuda;
    protected javax.swing.JMenuBar menuBarBarraMenus;
    protected javax.swing.JMenuItem menuCambiarFuente;
    protected javax.swing.JMenuItem menuCopiar;
    private javax.swing.JMenuItem menuCortar;
    protected javax.swing.JMenu menuEdicion;
    protected javax.swing.JMenuItem menuGuardar;
    protected javax.swing.JMenuItem menuGuardarComo;
    protected javax.swing.JMenuItem menuMostrarAyuda;
    private javax.swing.JMenuItem menuNuevo;
    protected javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
